"""empty message

Revision ID: 2faf0c2a5cb6
Revises: fdb491e64d62
Create Date: 2020-12-13 22:59:04.450938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2faf0c2a5cb6'
down_revision = 'fdb491e64d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'seekMessage')
    op.drop_column('artist', 'website_link')
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('show', 'show_datetime')
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('venue', 'seekMessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seekMessage', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('venue', 'seeking_description')
    op.add_column('show', sa.Column('show_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('seekMessage', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
