"""empty message

Revision ID: 5e2be8142c73
Revises: 2faf0c2a5cb6
Create Date: 2020-12-14 20:30:32.801878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2be8142c73'
down_revision = '2faf0c2a5cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_artist', sa.Boolean(), nullable=True))
    op.drop_column('venue', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_artist')
    # ### end Alembic commands ###
